eurec4a/how_to_eurec4a

- .gitlab-ci.yml
- requirements.txt
The root cause of previous build failures seems to be related to an
incompatible upgrade of the `sphinxcontrib-bibtex` package as also noted
in executablebooks/jupyter-book#1137. This pin can most likely be
removed once a new version of `jupyter-book` is available, either
because `jupyter-book` includes the pin in its dependencies or because it
adapts to the new requirements of `sphinxcontrib-bibtex`.
I've also removed the tag for the gitlab runner as it is very likely
that it was working on the one runner and not on the other because it
cached an older version of `sphinxcontrib-bibtex` and as soon as the
cache would be emptied the issue might arise again.
> pin version of sphinxcontrib-bibtex<2.0.0

- how_to_eurec4a/_toc.yml
- how_to_eurec4a/stats.md
While developing the book, this can be helpful to spot pages which
contain errors in the scripts.
> added page with script execution statistics

- requirements.txt
That ipfsspec release adds request slow down in case a gateway server
asks for slower requests (i.e. HTTP 429).
> upgrade ipfsspec to >= 0.0.2

- README.md
The book is hosted on gitlab, so this section is just plain wrong. Probably we should add a description on how it is actually hosted though... On the other hand, everything needed is stored within the .gitlab-ci.yml
> removed gh-pages section from README.md

- how_to_eurec4a/_toc.yml
- how_to_eurec4a/show_intake_catalog.md
This is just a small toolbox entry to show the tree structure of the intake catalog.
> toolbox: added intake tree

- requirements.txt
Since intake v0.6.1 which has just been released, the `to_dask()` function does not work anymore without requiring the `[dataframe]` section of the `intake` package. This change should fix the issue with currently failing builds.
> requirements: changed intake -> intake[dataframe]

- how_to_eurec4a/_config.yml
execute_notebooks should be in execute according to the docs
https://jupyterbook.org/customize/config.html?highlight=favicon#configuration-defaults
[See @d70-t  comment:](https://github.com/eurec4a/how_to_eurec4a/pull/36#discussion_r583919413)
```
[...] We should also find out what exactly will be changed using this fix.
* As we have switched from `.ipynb` notebooks to `MySt` notebooks, there actually aren't any pre-executed cells in the repository. Thus, `force`ing the execution doesn't make very much sense anyways.
* Currently, notebook cells are all executed in the Continuous Integration environment but cached on my local computer. This is exactly as I would like to have it, because it allows rapid development but with the guarantee that the cells which turn up in the book can actually …
```
> Fix config.execute

- how_to_eurec4a/_toc.yml
- how_to_eurec4a/multi_platform_data.md
JOANNE contains data measurements from multiple platforms but is currently listed under HALO. Why not have a category for "multi-platform datasets"?
> Add multi-platform datasets starting with JOANNE dropsondes

- .gitignore
- how_to_eurec4a/bacardi.md
- how_to_eurec4a/dropsondes.md
- how_to_eurec4a/flight_tracks_leaflet.md
- how_to_eurec4a/hamp_comparison.md
- how_to_eurec4a/meteor_cloudradar.md
- how_to_eurec4a/mplstyle/book
- how_to_eurec4a/mplstyle/wide
- how_to_eurec4a/references.bib
- how_to_eurec4a/smart.md
- how_to_eurec4a/specmacs.md
- how_to_eurec4a/unified.md
- how_to_eurec4a/velox.md
- how_to_eurec4a/wales.md
This PR contains several individual commits which are intended to clean up the currently existing notebooks a bit. Some things which are included are:
* `%pylab inline` is deprecated and should not be used. It is quite likely that I introduced this silly piece of code, I think it is time to get rid of it :-)
* The above required some more changes to plotting code, I took this as a chance and created matplotlib stylesheets in `/how_to_eurec4a/mplstyle`. That way, plots should get a more common appearance. I'd suggest to update styles in these files as long as anyhow possible. Currently there are two files, the `book` which contains basic styles for all plots and `wide` which contains a wider figure aspect ratio which can occasionally be useful.
* included the new HALO `PositionAttitude` …
> Some cleanups

- .github/workflows/buildbook.yaml
This PR adds a workflow job to publish the book on github pages. We should later be able to add a custom domain. Until that is the case, I would **not** jet consider the copy on github pages to be the "official" one.
relevant issue: #53
> publish book on GitHub pages

- how_to_eurec4a/_config.yml
- how_to_eurec4a/cloudmasks.md
Set the default time allowed for each notebook to 90 seconds but add metadata to the cloudmasks notebook to allow  300 seconds.
> Shorter timeout limit for notebooks, extended for one notebook

- how_to_eurec4a/cloudmasks.md
- how_to_eurec4a/mplstyle/square
- requirements.txt
The plots from the cloud mask chapter shall be part of the EUREC4A HALO ESSD paper (in preparation). From an internal review among the co-authors a few suggestions were made that lead to an update here. The main points were:
* we added a VELOX brightness temperature image to the case study plot on Feb 5.
* for the same figure, the VELOX cloud flag was based on the central 10x10 pixels and was extended to 11x11 pixels (~0.57°) to better match the specMACS (central 0.6°) and radar footprints.
* the time series plot had a bug in the errorbar calculation that was fixed
* campaign mean averages shall cover only local research flights
* further clean up and improvements
> Updates and corrections to the HALO cloudmask book chapter

- how_to_eurec4a/_toc.yml
- requirements.txt
The new jb version v0.11.0 has a new table of contents infrastructure. See the [webpage](https://jupyterbook.org/reference/_changelog.html) for more details.
> Update to jb 0.11.0 with new toc structure

- .github/workflows/buildbook.yaml
- environment.yml
pip-dependencies haven't been installed anymore on binder, because of a previous fix.
This PR (hopefully) fixes the root cause, which is pip beeing more strict about what the definition of a file-URI is.
In particular, it is not allowed to install dependecies via
```
pip install -r file:requirements.txt
```
but 
```
pip install -r requirements.txt
```
is still fine.
Due to this change, pip-dependencies can be again installed via conda and thus will also automatically be installed in binder again.
> Fix dependency installation

- how_to_eurec4a/c3ontext.md
- how_to_eurec4a/references.bib
Just a small update on the C3ONTEXT paper reference since the final paper is now published and should be cited instead of the preprint.
> Update C3ONTEXT publication reference to published version

- CONTRIBUTING.md
- LICENSE
- README.md
- how_to_eurec4a/HALO_instrument_overview.md
- how_to_eurec4a/_config.yml
- how_to_eurec4a/bacardi.md
- how_to_eurec4a/c3ontext.md
- how_to_eurec4a/cloudmasks.md
- how_to_eurec4a/dropsondes.md
- how_to_eurec4a/flight-phase-operations.md
- how_to_eurec4a/halo.md
- how_to_eurec4a/intro.md
- how_to_eurec4a/merian.md
- how_to_eurec4a/netcdf_datatypes.md
- how_to_eurec4a/p3_AXBTs.md
- how_to_eurec4a/p3_flight_tracks.md
- how_to_eurec4a/p3_humidity_comparison.md
- how_to_eurec4a/p3_wband_radar.md
- how_to_eurec4a/p3_wsra.md
- how_to_eurec4a/pthree.md
- how_to_eurec4a/simulations.md
- how_to_eurec4a/specmacs.md
- how_to_eurec4a/unified.md
- how_to_eurec4a/velox.md
Fixes #78 nearly everywhere, except for the GitHub repository's about section.
> Change spelling of EUREC4A to EUREC⁴A

- how_to_eurec4a/_toc.yml
- how_to_eurec4a/eurec4a_mip.md
- how_to_eurec4a/eurec4a_mip_submission.md
- requirements.txt
This PR adds a section about the EUREC4A-MIP effort on how to access boundary conditions, how to provide new model runs and how to access any available simulations.
> create EUREC4A-MIP entry

- .github/ISSUE_TEMPLATE/dataset--documentation--request.md
To make the HowTo-EUREC4A book issue tracker the central platform to communicate about datasets, this is one of several issue templates that shall make it easier for EUREC4A data users to request new documentation about datasets and request the addition of datasets to the eurec4a-intake catalog or the publication of a dataset in general.
The idea is that users try to find out the dataset contact person and that the core-team will contact them via email if they don't have a (known) GitHub-handle and are automatically notified about this issue. This way, it is ensured that dataset providers see the interest in their datasets.
> Add issue template for dataset requests

- how_to_eurec4a/botany_dales.md
@observingClouds @fjansson 
Three changes:
- Fixed an error in the `wpamp` range in the ranges table
- Added short description on how the `nx96` cases differ from `nx1536` (only in temporal coverage), incl. one example of loading a `nx96` data set
- Updated link to the visualisations page, so it now points to the Zenodo page where @fjansson stored them
Let me know what you think, happy to make further changes.
> Documenting Cloud Botany nx96 simulations

- .github/workflows/buildbook.yaml
This PR should setup github actions such that the notebook execution cache will always be saved (even in case of errors). To my understanding, jupyterbook will re-execute failed notebooks on the next build, but could reuse successfully executed notebook cells in that case. This should therefore give use a big improvement in average build time.
> always save execution cache

- .github/workflows/buildbook.yaml
- environment.yml
This PR
* uses the [matching rules for restore_keys](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) to be able to update the cache and thus fixes #104.
* It also adds caching for the conda environment (which uses mamba now) in a separate cache, thereby speeding up the environment creation.
* I thereby removed the python version from the build matrix, because `mamba update` seems to care only about what's written in `environment.yml` and we likely won't build the thing with different python versions concurrently.
* This change only upload the `html` part of the build output, which speeds up artifact creation and reduces required disk space. I don't think we ever used anything else, so it seems to be a more sensible …
> Cache improvements

- .github/workflows/buildbook.yaml
- how_to_eurec4a/intro.md
This change adds information on how to set up a local environment to use EUREC4A data in own code. I.e.:
* to install all dependencies for getting the data (`pip install eurec4a[data]`)
* to set up a local IPFS node for reasonable performance
> Intro: how to actually access data in a local environment

- how_to_eurec4a/eurec4a_mip_submission.md
The token generation for the DKRZ-Swiftstore was not completely correct. The swift-token.py helper script from DKRZ is now linked and described instead of the less user-friendly `curl` method.
> Update TOKEN generation instructions
